/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Idempotent session upsert triggered by frontend OAuth callback */
        post: operations["syncUserSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List paginated content items owned by the authenticated user */
        get: operations["listContent"];
        put?: never;
        /** Ingest text payload and dispatch asynchronous worker task */
        post: operations["createContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch absolute content details or ongoing progress metrics */
        get: operations["getContentDetail"];
        put?: never;
        post?: never;
        /** Purge saved study content records */
        delete: operations["deleteContent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fan-out SSE stream emitting progress updates for all active content items owned by the authenticated user */
        get: operations["streamContentProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            detail: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string | null;
            name?: string | null;
            /** Format: uri */
            image?: string | null;
        };
        /** @enum {string} */
        JLPTLevel: "N1" | "N2" | "N3" | "N4" | "N5";
        LevelDistribution: {
            N1: number;
            N2: number;
            N3: number;
            N4: number;
            N5: number;
        };
        Sentence: {
            text: string;
            translation: string;
            level: components["schemas"]["JLPTLevel"];
            grammar_points: string[];
            similar_patterns: string[];
        };
        VocabularyItem: {
            word: string;
            reading: string;
            level: components["schemas"]["JLPTLevel"];
            translation: string;
            synonyms: string[];
            example_phrases: string[];
        };
        BaseContent: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
            input_text: string;
            /** Format: date-time */
            created_at: string;
            title?: string | null;
        };
        ProcessingContent: components["schemas"]["BaseContent"] & {
            /**
             * @description Value from 0 to 99 representing worker execution status
             * @example 33
             */
            progress: number;
            /**
             * @description Human-readable label of the currently executing pipeline step
             * @example Evaluating Vocabulary Structures
             */
            current_step?: string | null;
            /** Format: date-time */
            estimated_completion_time?: string | null;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "PENDING" | "PROCESSING";
        };
        FailedContent: components["schemas"]["BaseContent"] & {
            /** @example LLM synthesis timeout encountered. */
            error_message: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "FAILED";
        };
        CompletedContent: components["schemas"]["BaseContent"] & {
            overall_level: components["schemas"]["JLPTLevel"];
            level_distribution: components["schemas"]["LevelDistribution"];
            sentences: components["schemas"]["Sentence"][];
            vocabulary: components["schemas"]["VocabularyItem"][];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "COMPLETED";
        };
        Content: components["schemas"]["ProcessingContent"] | components["schemas"]["FailedContent"] | components["schemas"]["CompletedContent"];
        CreateContentRequest: {
            text: string;
            title?: string | null;
        };
        ContentProgressEvent: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
            /** @description 0–99 during processing, null otherwise */
            progress?: number | null;
            /** @description Human-readable label of the currently executing pipeline step */
            current_step?: string | null;
        };
    };
    responses: {
        /** @description Session missing or invalid token signature */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Data isolation boundary controls violated */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Target asset not matching persistent indexes */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    syncUserSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example google */
                    provider: string;
                    /** @example 1234567890 */
                    providerAccountId: string;
                    /** Format: email */
                    email: string | null;
                    /** @example Hong Gil Dong */
                    name?: string;
                    /** Format: uri */
                    image?: string | null;
                };
            };
        };
        responses: {
            /** @description Identity synchronized successfully. Returns session details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Invalid payload configuration */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user records matching the verified session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listContent: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated collection envelope containing processing and completed entities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Content"][];
                        meta: {
                            total: number;
                            page: number;
                            limit: number;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createContent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContentRequest"];
            };
        };
        responses: {
            /** @description Ingestion job accepted. Returns intermediate polymorphic record. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingContent"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Input constraints violated */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getContentDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Polished detail context mapping exactly to lifecycle state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Content"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Target resource successfully purged */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    streamContentProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream. Connection closes when no more items are PENDING or PROCESSING. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ContentProgressEvent"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
